session: fix SessionState.persistent_save()
This function created a NamedTemporaryFile in text mode without specifying
the encoding, thus it silently depended on locale to fall-back to UTF-8.
This broke in the SRU CI loop as seen in the following backtrace:

  File "/usr/lib/python3/dist-packages/plainbox/impl/commands/sru.py", line 118, in _run_all_jobs
    self.session.persistent_save()
  File "/usr/lib/python3/dist-packages/plainbox/impl/session.py", line 566, in persistent_save
    ensure_ascii=False, indent=None, separators=(',', ':'))
  File "/usr/lib/python3.2/json/__init__.py", line 179, in dump
    fp.write(chunk)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1-2: ordinal not in range(256)

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>